local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node

return {
  s("!tsconfig", {
    t({
      '"$schema": "https://www.schemastore.org/tsconfig.json",',
    }),
  }),
  s(
    "!tscomp-basic",
    t({
      '"compilerOptions": {',
      '  "allowImportingTsExtensions": true,',
      '  "jsx": "react-jsx",',
      '  "jsxImportSource": "preact",',
      '  "noUnusedLocals": true,',
      '  "noUnusedParameters": true,',
      "",
      "  // Source - https://stackoverflow.com/a/53836076",
      "  // Posted by sebilasse",
      "  // Retrieved 2026-07-08, License - CC BY-SA 4.0",
      "  //",
      "  // INFO: Uncomment if you want to import package.json",
      '  // "resolveJsonModule": true,',
      '  // "esModuleInterop": true,',
      '  // "module": "commonjs"',
      "}",
    })
  ),
  s(
    "!tscomp",
    t({
      '"compilerOptions": {',
      '  "jsx": "react-jsx",',
      '  "jsxImportSource": "preact",',
      '  "allowImportingTsExtensions": true,',
      '  "allowUnusedLabels": false,',
      '  "noUnusedLocals": true,',
      '  "noUnusedParameters": true,',
      '  "noUncheckedSideEffectImports": true,',
      '  "noFallthroughCasesInSwitch": true,',
      '  "allowUnreachableCode": false,',
      '  "noImplicitOverride": true,',
      '  "erasableSyntaxOnly": true,',
      '  "exactOptionalPropertyTypes": true,',
      '  // "noPropertyAccessFromIndexSignature": true,',
      '  // "noUncheckedIndexedAccess": true, // Disallow null and undefined to be equal in type check',
      "",
      "  // Source - https://stackoverflow.com/a/53836076",
      "  // Posted by sebilasse",
      "  // Retrieved 2026-07-08, License - CC BY-SA 4.0",
      "  //",
      "  // INFO: Uncomment if you want to import package.json",
      '  // "resolveJsonModule": true,',
      '  // "esModuleInterop": true,',
      '  // "module": "commonjs"',
      "}",
    })
  ),

  s("!biome", {
    t({
      "{",
      '  "$schema": "./node_modules/@biomejs/biome/configuration_schema.json",',
      '  "vcs": {',
      '    "enabled": true,',
      '    "clientKind": "git",',
      '    "useIgnoreFile": true',
      "  },",
      '  "files": {',
      '    "ignoreUnknown": true',
      "  },",
      '  "formatter": {',
      '    "enabled": true,',
      '    "lineWidth": 80,',
      '    "indentStyle": "space"',
      "  },",
      '  "linter": {',
      '    "enabled": true,',
      '    "rules": {',
      '      "correctness": {',
      '        "noUnusedVariables": "off",',
      '        "noUnusedFunctionParameters": "off"',
      "      },",
      '      "nursery": {',
      '        "useSortedClasses": "on"',
      "      }",
      "    }",
      "  },",
      '  "javascript": {',
      '    "formatter": {',
      '      "quoteStyle": "double"',
      "    }",
      "  },",
      '  "assist": {',
      '    "enabled": true,',
      '    "actions": {',
      '      "source": {',
      '        "organizeImports": "on"',
      "      }",
      "    }",
      "  },",
      '  "css": {',
      '    "parser": {',
      '      "tailwindDirectives": true',
      "    }",
      "  }",
      "}",
    }),
  }),
}
