local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node

return {
  s("!tsconfig", {
    t({
      '"$schema": "https://www.schemastore.org/tsconfig.json",',
    }),
  }),

  s("!tscomp", {
    t({
      '"compilerOptions": {',
      '  "jsx": "react-jsx",',
      '  "allowImportingTsExtensions": true,',
      '  "allowUnusedLabels": false,',
      '  "noUncheckedSideEffectImports": true,',
      '  "noFallthroughCasesInSwitch": true,',
      '  "allowUnreachableCode": false,',
      '  "noUncheckedIndexedAccess": true,',
      '  "noPropertyAccessFromIndexSignature": true,',
      '  "noImplicitOverride": true,',
      '  "erasableSyntaxOnly": true,',
      '  "exactOptionalPropertyTypes": true',
      "}",
    }),
  }),

  s("!biome", {
    t({
      "{",
      '  "$schema": "./node_modules/@biomejs/biome/configuration_schema.json",',
      '  "vcs": {',
      '    "enabled": true,',
      '    "clientKind": "git",',
      '    "useIgnoreFile": true',
      "  },",
      '  "files": {',
      '    "ignoreUnknown": true',
      "  },",
      '  "formatter": {',
      '    "enabled": true,',
      '    "lineWidth": 80,',
      '    "indentStyle": "space"',
      "  },",
      '  "linter": {',
      '    "enabled": true,',
      '    "rules": {',
      '      "correctness": {',
      '        "noUnusedVariables": "off",',
      '        "noUnusedFunctionParameters": "off"',
      "      },",
      '      "nursery": {',
      '        "useSortedClasses": "on"',
      "      }",
      "    }",
      "  },",
      '  "javascript": {',
      '    "formatter": {',
      '      "quoteStyle": "double"',
      "    }",
      "  },",
      '  "assist": {',
      '    "enabled": true,',
      '    "actions": {',
      '      "source": {',
      '        "organizeImports": "on"',
      "      }",
      "    }",
      "  },",
      '  "css": {',
      '    "parser": {',
      '      "tailwindDirectives": true',
      "    }",
      "  }",
      "}",
    }),
  }),
}
